# Generated by Django 3.1.5 on 2021-01-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0005_auto_20210121_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
