# Generated by Django 3.1.5 on 2021-01-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0006_auto_20210121_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
